name: Game Test

on:
  push:
    branches: [ "kotlin-migration" ]
  pull_request:
    branches: [ "kotlin-migration" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Compile
        run: ./kotlin test